pipeline {
    agent { docker { image 'python:3.10.13-slim-bookworm' } }
    stages {
        stage('Build') {
            steps {
                sh 'python3 --version'
            }
        }
        stage('Git Pulling') {
            steps {
                echo 'Git'
                git(
                    url: "https://github.com/YsmanKhamidullin/ML-OPS",
                    branch: "main",
                    changelog: true
                )
            }
        }

        stage('Runnin ML Pipeline') {
            steps {
                sh '''
                    python3 -m venv ./venv
                    . venv/bin/activate
                    pip3 install -r requirements.txt
                    cd ./lab1/
                    ./pipeline.sh
                '''
            }

        }
    }
}
